### ISSUE TITLE
If llm logs are turned off, using command-r-search gives an error

### ISSUE THREAD

**Issue by kintopp** [simonw/llm-command-r#5]
```
Traceback (most recent call last):
  File "/Users/abosse/.local/bin/llm", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/abosse/Library/Application Support/pipx/venvs/llm/lib/python3.11/site-packages/llm_command_r.py", line 52, in command_r_search
    if (logs_on() or log) and not no_log:
                     ^^^
NameError: name 'log' is not defined
```

Turn llm logs back on, and all is well.

**Comment by kintopp** [comment]
Turn llm logs back on, and all is well.

**Comment by simonw** [comment]
Fixed:
```bash
llm command-r-search 'simon willison latest post' -n
```

> Simon Willison's latest post on his weblog is titled *Qwen2.5-VL-32B: Smarter and Lighter*. In the post, he talks about his simonw/shot-scraper-scripts repo and how the amount of work involved in modifying all the parts of his site that handle the three different content types was daunting. He also mentions the new Gemini 2.5 Pro model. The post ends with an invitation for readers to share their own shot-scraper-scripts repos.
